name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      tag_as_latest:
        type: choice
        description: 'Tag as latest (true/false)'
        required: false
        default: false
        options: 
          - true
          - false
  push:
    branches:
      - develop
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(-RC-[0-9]+)'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Vars
        id: vars
        run: |
          ::set-output name=is_rc::$(echo ${{ github.ref }} | grep -E 'v[0-9]+\.[0-9]+\.[0-9]+-RC[0-9]+')
          ::set-output name=tag_name::$(echo ${{ github.ref }} | sed 's/^refs\/heads\///' | sed 's/^refs\/tags\///')
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: pentaho-pdi-kitchen
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build
        if: steps.vars.outputs.is_rc == ''
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/main/docker/Dockerfile
          tags: pentaho-pdi-kitchen:${{ steps.vars.outputs.tag_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Build and export
        if: steps.vars.outputs.is_rc != ''
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/main/docker/Dockerfile
          tags: pentaho-pdi-kitchen:${{ steps.vars.outputs.tag_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          outputs: type=docker,dest=/tmp/pentaho-pdi-kitchen.tar

      - name: Upload artifact
        if: steps.vars.outputs.is_rc != ''
        uses: actions/upload-artifact@v3
        with:
          name: pentaho-pdi-kitchen-image
          path: /tmp/pentaho-pdi-kitchen.tar

      - name: Move cache avoid forever growth
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
