name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      tag_as_latest:
        type: choice
        description: 'Tag as latest (true/false)'
        required: false
        default: false
        options: 
          - true
          - false
  push:
    branches:
      - develop
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(-RC-[0-9]+)'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Vars
        id: vars
        run: |
          echo ::set-output name=tag::$(${GITHUB_REF#refs/*/}$) >> $GITHUB_OUTPUT
          echo ::set-output name=is_rc::$(echo ${{ github.ref }} | grep -E 'v[0-9]+\.[0-9]+\.[0-9]+-RC[0-9]+') >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/main/docker/Dockerfile
          tags: pentaho-pdi-kitchen:latest
          outputs: type=docker,dest=/tmp/pentaho-pdi-kitchen.tar

